# Generated by Django 4.2.23 on 2025-10-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_payments_chapa_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='chapa_response',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='email',
        ),
        migrations.AlterField(
            model_name='payments',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.booking'),
        ),
    ]
