# Generated by Django 4.2.23 on 2025-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "listings",
            "0005_remove_payments_chapa_response_remove_payments_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
