# Generated by Django 4.2.23 on 2025-11-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_booking_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="listings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="listings.listing",
            ),
        ),
    ]
