# Generated by Django 4.2.23 on 2025-10-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_booking_user_alter_payments_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='chapa_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
