# Generated by Django 4.2.23 on 2025-10-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_payments_chapa_response_payments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='chapa_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
